<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SelectiveTrickplay</RootNamespace>
    <AssemblyName>SelectiveTrickplay</AssemblyName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Common" Version="10.9.0" />
    <PackageReference Include="MediaBrowser.Controller" Version="10.9.0" />
    <PackageReference Include="MediaBrowser.Model" Version="10.9.0" />
    <PackageReference Include="MediaBrowser.Common" Version="10.9.0" />
  </ItemGroup>

</Project>
